DROP TABLE BANK_ACCOUNT IF EXISTS
DROP TABLE INSURANCE_ACCOUNT IF EXISTS
CREATE TABLE BANK_ACCOUNT (
BANK_ID INT,
BANK_AMOUNT INT,
PRIMARY KEY(BANK_ID));

CREATE TABLE INSURANCE_ACCOUNT (
INSURANCE_ID INT,
INSURANCE_AMOUNT INT,
PRIMARY KEY(INSURANCE_ID));

INSERT INTO BANK_ACCOUNT VALUES (1111, 1000);
INSERT INTO INSURANCE_ACCOUNT VALUES (2222, 1000);