DROP DATABASE IF EXISTS java_transaction_workshop
CREATE DATABASE java_transaction_workshop DEFAULT CHARACTER SET utf8;
USE java_transaction_workshop

CREATE TABLE BANK_ACCOUNT (
BANK_ID INT,
BANK_AMOUNT INT,
PRIMARY KEY(BANK_ID)
);

CREATE TABLE INSURANCE_ACCOUNT (
INSURANCE_ID INT,
INSURANCE_AMOUNT INT,
PRIMARY KEY(INSURANCE_ID)
);

INSERT INTO BANK_ACCOUNT VALUES (1111, 1000);
INSERT INTO INSURANCE_ACCOUNT VALUES (2222, 1000);